//!zig-autodoc-section: textures_raw_data.Main
//! raylib_examples/textures_raw_data.zig
//!   Example - automation events.
//!
//! raylib Copyright (c) 2013-2024 Ramon Santamaria (@raysan5)
//! Zig port created by DarknessFX | https://dfx.lv | X @DrkFX

// /*******************************************************************************************
// *
// *   raylib [textures] example - Load textures from raw data
// *
// *   NOTE: Images are loaded in CPU memory (RAM); textures are loaded in GPU memory (VRAM)
// *
// *   Example originally created with raylib 1.3, last time updated with raylib 3.5
// *
// *   Example licensed under an unmodified zlib/libpng license, which is an OSI-certified,
// *   BSD-like license that allows static linking with closed source software
// *
// *   Copyright (c) 2015-2024 Ramon Santamaria (@raysan5)
// *
// ********************************************************************************************/

const std = @import("std");

// NOTE ABOUT VSCODE + ZLS:
// Use full path for all cIncludes:
//   @cInclude("C:/raylib_examples/lib/raylib.h"); 
const ray = @cImport({ 
  @cInclude("raylib.h"); 
});

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
pub fn main() !u8 {
  // Initialization
  //--------------------------------------------------------------------------------------
  const screenWidth: c_int = 800;
  const screenHeight: c_int = 450;

  ray.InitWindow(screenWidth, screenHeight, "raylib [textures] example - texture from raw data");

  // NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)

  // Load RAW image data (512x512, 32bit RGBA, no file header)
  const fudesumiRaw = ray.LoadImageRaw(getPath("textures", "resources/fudesumi.raw"), 384, 512, ray.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 0);
  const fudesumi = ray.LoadTextureFromImage(fudesumiRaw);  // Upload CPU (RAM) image to GPU (VRAM)
  ray.UnloadImage(fudesumiRaw);                                // Unload CPU (RAM) image data

  // Generate a checked texture by code
  const width = 960;
  const height = 480;

  // Dynamic memory allocation to store pixels data (Color type)
  const pixels: [*]ray.Color = @ptrCast(std.c.malloc(width * height * @sizeOf(ray.Color)));

  for (0..height) |y| {
      for (0..width) |x| {
          if (((@divTrunc(x, 32) + @divTrunc(y, 32)) / 1) % 2 == 0) pixels[@intCast(y * width + x)] = ray.ORANGE
          else pixels[y * width + x] = ray.GOLD;
      }
  }

  // Load pixels data into an image structure and create texture
  const checkedIm = ray.Image{
    .data = pixels,             // We can assign pixels directly to data
    .width = width,
    .height = height,
    .format = ray.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
    .mipmaps = 1,
  };

  const checked = ray.LoadTextureFromImage(checkedIm);
  ray.UnloadImage(checkedIm);         // Unload CPU (RAM) image data (pixels)

  ray.SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
  //---------------------------------------------------------------------------------------

  // Main game loop
  while (!ray.WindowShouldClose())    // Detect window close button or ESC key
  {
    // Update
    //----------------------------------------------------------------------------------
    // TODO: Update your variables here
    //----------------------------------------------------------------------------------

    // Draw
    //----------------------------------------------------------------------------------
    ray.BeginDrawing();

      ray.ClearBackground(ray.RAYWHITE);

      ray.DrawTexture(checked, 
        @divTrunc(screenWidth, 2) - @divTrunc(checked.width, 2), 
        @divTrunc(screenHeight, 2) - @divTrunc(checked.height, 2), ray.Fade(ray.WHITE, 0.5));

      ray.DrawTexture(fudesumi, 430, -30, ray.WHITE);

      ray.DrawText("CHECKED TEXTURE ", 84, 85, 30, ray.BROWN);
      ray.DrawText("GENERATED by CODE", 72, 148, 30, ray.BROWN);
      ray.DrawText("and RAW IMAGE LOADING", 46, 210, 30, ray.BROWN);

      ray.DrawText("(c) Fudesumi sprite by Eiden Marsal", 310, screenHeight - 20, 10, ray.BROWN);

    ray.EndDrawing();
    //----------------------------------------------------------------------------------
  }

  // De-Initialization
  //--------------------------------------------------------------------------------------
  ray.UnloadTexture(fudesumi);    // Texture unloading
  ray.UnloadTexture(checked);     // Texture unloading

  ray.CloseWindow();              // Close window and OpenGL context
  //--------------------------------------------------------------------------------------
  return 0;
}

//------------------------------------------------------------------------------------
// Helpers
//------------------------------------------------------------------------------------
inline fn toFloat(value: i32) f32 { return @as(f32, @floatFromInt(value));}
inline fn toFloatC(value: c_int) f32 { return @as(f32, @floatFromInt(value));}
inline fn toInt(value: f32) i32 { return @as(i32, @intFromFloat(value));}
inline fn toU8(value: c_int) u8 { return @as(u8, @intCast(value));}
inline fn fmt(comptime format: []const u8, args: anytype) []u8 {  return std.fmt.allocPrint(std.heap.page_allocator, format, args) catch unreachable; }
inline fn fmtC(comptime format: []const u8, args: anytype) [:0]u8 {  return std.fmt.allocPrintZ(std.heap.page_allocator, format, args) catch unreachable; }

var cwd: []u8 = undefined;
inline fn getCwd() []u8 { return std.process.getCwdAlloc(std.heap.page_allocator) catch unreachable; }
inline fn getPath(folder: []const u8, file: []const u8) [*]const u8 { 
  if (cwd.len == 0) cwd = getCwd();
  std.fs.cwd().access(folder, .{ .mode = std.fs.File.OpenMode.read_only }) catch {
    return fmt("{s}/{s}", .{ cwd, file} ).ptr; 
  };
  return fmt("{s}/{s}/{s}", .{ cwd, folder, file} ).ptr; 
}